<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.microinfra</groupId>
		<artifactId>microinfra-parent</artifactId>
		<version>1.0.0</version>
	</parent>

	<artifactId>microinfra-shortlink</artifactId>
	<packaging>pom</packaging>
	<name>microinfra-shortlink</name>
	<description>shortlink service module</description>

	<modules>
		<module>shortlink-commons</module>
		<module>shortlink-core</module>
		<module>shortlink-client</module>
		<module>shortlink-server</module>
		<module>build</module>
	</modules>
</project>
