<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.microinfra</groupId>
	<artifactId>microinfra-parent</artifactId>
	<version>1.0.0</version>
	<packaging>pom</packaging>
	<name>microinfra-parent</name>
	<description>project dependencies and plugin management</description>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>

		<maven.antrun.plugin.version>3.1.0</maven.antrun.plugin.version>
		<maven.compiler.plugin.version>3.8.1</maven.compiler.plugin.version>
		<maven.resources.plugin.version>3.1.0</maven.resources.plugin.version>
		<maven.replacer.plugin.version>1.5.3</maven.replacer.plugin.version>
		<maven.enforcer.plugin.version>3.1.0</maven.enforcer.plugin.version>
		<maven.dependency.plugin.version>3.2.0</maven.dependency.plugin.version>
		<exec.maven.plugin.version>3.0.0</exec.maven.plugin.version>
		<maven.source.plugin.version>3.2.1</maven.source.plugin.version>
		<maven.jar.plugin.version>3.2.0</maven.jar.plugin.version>
		<maven.assembly.plugin.version>3.2.0</maven.assembly.plugin.version>
		<maven.surefire.plugin.version>3.0.0-M4</maven.surefire.plugin.version>
		<maven.install.plugin.version>3.0.0-M1</maven.install.plugin.version>
		<maven.release.plugin.version>3.0.0-M4</maven.release.plugin.version>
		<maven.springboot.plugin.version>2.2.7.RELEASE</maven.springboot.plugin.version>
		<maven.sonar.plugin.version>3.8.0.2131</maven.sonar.plugin.version>
		<maven.toolchains.plugin.version>3.2.0</maven.toolchains.plugin.version>

		<spring.cloud.release.version>2021.0.5</spring.cloud.release.version>
		<spring.cloud.alibaba.version>2021.0.6.2</spring.cloud.alibaba.version>
		<spring.boot.version>2.6.13</spring.boot.version>

		<logback.version>1.2.11</logback.version><!-- 根据spring-boot-starter依赖的logback版本来确定 -->
		<validation.api.version>2.0.2</validation.api.version><!-- 根据spring-boot-starter-validation依赖的validation-api版本来确定 -->
		<lombok.version>1.18.20</lombok.version>
		<swagger.version>2.9.2</swagger.version>
		<swagger.models.version>1.6.11</swagger.models.version>
		<swagger.bootstrapui.version>1.9.6</swagger.bootstrapui.version>
		<mysql.connector.version>8.0.32</mysql.connector.version>
		<alibaba.druid.version>1.2.6</alibaba.druid.version>
		<pagehelper.starter.version>1.4.2</pagehelper.starter.version>
		<pagehelper.version>5.3.0</pagehelper.version>
		<mybatisplus.starter.version>3.5.2</mybatisplus.starter.version>
		<mybatis.plus.code.generator.version>3.5.0</mybatis.plus.code.generator.version>
		<velocity.engine.core.version>2.3</velocity.engine.core.version>

		<hutool.version>5.8.22</hutool.version>
		<alibaba.fastjson2.version>2.0.42</alibaba.fastjson2.version>
		<alibaba.easyexcel.version>3.0.5</alibaba.easyexcel.version>
		<alibaba.ttl.version>2.14.5</alibaba.ttl.version>
		<aliyunsdk.oss.version>3.17.4</aliyunsdk.oss.version>
		<google.guava.version>31.1-jre</google.guava.version>
		<redisson.starter.version>3.16.8</redisson.starter.version>
		<rocketmq.starter.version>2.3.0</rocketmq.starter.version>
		<spring.mqtt.version>5.5.14</spring.mqtt.version>
		<org.mapstruct.version>1.5.5.Final</org.mapstruct.version>
		<ignite.version>2.17.0</ignite.version>
		<h2.version>1.4.197</h2.version>
		<caffeine.version>2.9.3</caffeine.version>
		<lucene.version>9.12.3</lucene.version>

		<kaptcha.version>2.3.2</kaptcha.version>
		<jsonwebtoken.jjwt.version>0.9.1</jsonwebtoken.jjwt.version>
		<hsr.geohash.version>1.4.0</hsr.geohash.version>
		<thingshub.client.version>1.0.0</thingshub.client.version>
		
		<microinfra.parent.version>1.0.0</microinfra.parent.version>
		<microinfra.commons.version>1.0.0</microinfra.commons.version>
		
		<microinfra.uid.version>1.0.0</microinfra.uid.version>
		<microinfra.store.version>1.0.0</microinfra.store.version>
		<microinfra.shortlink.version>1.0.0</microinfra.shortlink.version>
		<microinfra.search.version>1.0.0</microinfra.search.version>
		<microinfra.scheduler.version>1.0.0</microinfra.scheduler.version>
		<microinfra.push.version>1.0.0</microinfra.push.version>
		<microinfra.report.version>1.0.0</microinfra.report.version>
		<microinfra.rulengine.version>1.0.0</microinfra.rulengine.version>
		<microinfra.workflow.version>1.0.0</microinfra.workflow.version>
		
		<microinfra.sysiam.version>1.0.0</microinfra.sysiam.version>
		<microinfra.order.version>1.0.0</microinfra.order.version>
		<microinfra.payment.version>1.0.0</microinfra.payment.version>
		<microinfra.promotion.version>1.0.0</microinfra.promotion.version>
		<microinfra.parking.version>1.0.0</microinfra.parking.version>
		<microinfra.charging.version>1.0.0</microinfra.charging.version>
		
		<microinfra.gateway.version>1.0.0</microinfra.gateway.version>
		<microinfra.passport.version>1.0.0</microinfra.passport.version>		
		<microinfra.admin.version>1.0.0</microinfra.admin.version>
		<microinfra.operation.version>1.0.0</microinfra.operation.version>
		<microinfra.finance.version>1.0.0</microinfra.finance.version>
		<microinfra.custservice.version>1.0.0</microinfra.custservice.version>
		
		<microinfra.cashier.version>1.0.0</microinfra.cashier.version>		
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring.cloud.release.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>com.alibaba.cloud</groupId>
				<artifactId>spring-cloud-alibaba-dependencies</artifactId>
				<version>${spring.cloud.alibaba.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>${spring.boot.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>ch.qos.logback</groupId>
      			<artifactId>logback-classic</artifactId>
				<version>${logback.version}</version>
			</dependency>
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>${lombok.version}</version>
			</dependency>
			<dependency>
				<groupId>jakarta.validation</groupId>
		    <artifactId>jakarta.validation-api</artifactId>
		    <version>${validation.api.version}</version>
	    </dependency>
			<dependency>
				<groupId>io.springfox</groupId>
				<artifactId>springfox-swagger2</artifactId>
				<version>${swagger.version}</version>
			</dependency>
			<dependency>
				<groupId>io.swagger</groupId>
				<artifactId>swagger-models</artifactId>
				<version>${swagger.models.version}</version>
			</dependency>
			<dependency>
				<groupId>com.github.xiaoymin</groupId>
				<artifactId>swagger-bootstrap-ui</artifactId>
				<version>${swagger.bootstrapui.version}</version>
			</dependency>
			<dependency>
				<groupId>mysql</groupId>
				<artifactId>mysql-connector-java</artifactId>
				<version>${mysql.connector.version}</version>
			</dependency>
			<dependency>
				<groupId>com.alibaba</groupId>
				<artifactId>druid-spring-boot-starter</artifactId>
				<version>${alibaba.druid.version}</version>
			</dependency>
			<dependency>
				<groupId>com.github.pagehelper</groupId>
				<artifactId>pagehelper-spring-boot-starter</artifactId>
				<version>${pagehelper.starter.version}</version>
			</dependency>
			<dependency>
				<groupId>com.github.pagehelper</groupId>
				<artifactId>pagehelper</artifactId>
				<version>${pagehelper.version}</version>
			</dependency>
			<dependency>
				<groupId>com.baomidou</groupId>
				<artifactId>mybatis-plus-boot-starter</artifactId>
				<version>${mybatisplus.starter.version}</version>
			</dependency>
			<dependency>
				<groupId>com.baomidou</groupId>
				<artifactId>mybatis-plus-generator</artifactId>
				<version>${mybatis.plus.code.generator.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.velocity</groupId>
				<artifactId>velocity-engine-core</artifactId>
				<version>${velocity.engine.core.version}</version>
			</dependency>

			<dependency>
				<groupId>cn.hutool</groupId>
				<artifactId>hutool-core</artifactId>
				<version>${hutool.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.hutool</groupId>
				<artifactId>hutool-http</artifactId>
				<version>${hutool.version}</version>
			</dependency>
			<dependency>
				<groupId>cn.hutool</groupId>
				<artifactId>hutool-crypto</artifactId>
				<version>${hutool.version}</version>
			</dependency>
			<dependency>
				<groupId>com.alibaba.fastjson2</groupId>
				<artifactId>fastjson2</artifactId>
				<version>${alibaba.fastjson2.version}</version>
			</dependency>
			<dependency>
				<groupId>com.alibaba.fastjson2</groupId>
				<artifactId>fastjson2-extension-spring5</artifactId>
				<version>${alibaba.fastjson2.version}</version>
			</dependency>
			<dependency>
				<groupId>com.alibaba</groupId>
				<artifactId>easyexcel</artifactId>
				<version>${alibaba.easyexcel.version}</version>
			</dependency>
			<dependency>
				<groupId>com.alibaba</groupId>
				<artifactId>transmittable-thread-local</artifactId>
				<version>${alibaba.ttl.version}</version>
			</dependency>
			<dependency>
				<groupId>com.aliyun.oss</groupId>
				<artifactId>aliyun-sdk-oss</artifactId>
				<version>${aliyunsdk.oss.version}</version>
			</dependency>
			<dependency>
				<groupId>com.google.guava</groupId>
				<artifactId>guava</artifactId>
				<version>${google.guava.version}</version>
			</dependency>
			<dependency>
				<groupId>org.redisson</groupId>
				<artifactId>redisson-spring-boot-starter</artifactId>
				<version>${redisson.starter.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.rocketmq</groupId>
				<artifactId>rocketmq-spring-boot-starter</artifactId>
				<version>${rocketmq.starter.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.integration</groupId>
				<artifactId>spring-integration-mqtt</artifactId>
				<version>${spring.mqtt.version}</version>
			</dependency>
			<dependency>
				<groupId>org.mapstruct</groupId>
				<artifactId>mapstruct</artifactId>
				<version>${org.mapstruct.version}</version>
			</dependency>
			<dependency>
				<groupId>org.mapstruct</groupId>
				<artifactId>mapstruct-processor</artifactId>
				<version>${org.mapstruct.version}</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>org.apache.ignite</groupId>
				<artifactId>ignite-core</artifactId>
				<version>${ignite.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.ignite</groupId>
				<artifactId>ignite-slf4j</artifactId>
				<version>${ignite.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.ignite</groupId>
				<artifactId>ignite-urideploy</artifactId>
				<version>${ignite.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.ignite</groupId>
				<artifactId>ignite-indexing</artifactId>
				<version>${ignite.version}</version>
				<exclusions>
					<exclusion>
						<groupId>com.h2database</groupId>
						<artifactId>h2</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>com.h2database</groupId>
				<artifactId>h2</artifactId>
				<version>${h2.version}</version>
			</dependency>
			<dependency>
				<groupId>com.github.penggle</groupId>
				<artifactId>kaptcha</artifactId>
				<version>${kaptcha.version}</version>
				<exclusions>
					<exclusion>
						<artifactId>javax.servlet-api</artifactId>
						<groupId>javax.servlet</groupId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>io.jsonwebtoken</groupId>
				<artifactId>jjwt</artifactId>
				<version>${jsonwebtoken.jjwt.version}</version>
			</dependency>
			<dependency>
				<groupId>ch.hsr</groupId>
				<artifactId>geohash</artifactId>
				<version>${hsr.geohash.version}</version>
			</dependency>
			<dependency>
				<groupId>com.github.ben-manes.caffeine</groupId>
				<artifactId>caffeine</artifactId>
				<version>${caffeine.version}</version>
			</dependency>			
			<dependency>
        		<groupId>org.apache.lucene</groupId>
        		<artifactId>lucene-core</artifactId>
        		<version>${lucene.version}</version>
    		</dependency>
		    <dependency>
		        <groupId>org.apache.lucene</groupId>
		        <artifactId>lucene-queryparser</artifactId>
		        <version>${lucene.version}</version>
		    </dependency>
		    <dependency>
		        <groupId>org.apache.lucene</groupId>
		        <artifactId>lucene-highlighter</artifactId>
		        <version>${lucene.version}</version>
		    </dependency>
		    <dependency>
		        <groupId>io.thingshub</groupId>
		        <artifactId>thingshub-client</artifactId>
		        <version>${thingshub.client.version}</version>
		    </dependency>
		    
		    
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>commons-lang</artifactId>
				<version>${microinfra.commons.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>commons-model</artifactId>
				<version>${microinfra.commons.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>commons-ignite</artifactId>
				<version>${microinfra.commons.version}</version>
			</dependency>		
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>commons-rpc</artifactId>
				<version>${microinfra.commons.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>framework</artifactId>
				<version>${microinfra.commons.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>commons-auth</artifactId>
				<version>${microinfra.commons.version}</version>
			</dependency>
			
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>uid-commons</artifactId>
				<version>${microinfra.uid.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>uid-core</artifactId>
				<version>${microinfra.uid.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>uid-client</artifactId>
				<version>${microinfra.uid.version}</version>
			</dependency>
			
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>store-commons</artifactId>
				<version>${microinfra.store.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>store-core</artifactId>
				<version>${microinfra.store.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>store-client</artifactId>
				<version>${microinfra.store.version}</version>
			</dependency>
			
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>shortlink-commons</artifactId>
				<version>${microinfra.shortlink.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>shortlink-core</artifactId>
				<version>${microinfra.shortlink.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>shortlink-client</artifactId>
				<version>${microinfra.shortlink.version}</version>
			</dependency>
			
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>search-commons</artifactId>
				<version>${microinfra.search.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>search-core</artifactId>
				<version>${microinfra.search.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>search-client</artifactId>
				<version>${microinfra.search.version}</version>
			</dependency>
			
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>scheduler-commons</artifactId>
				<version>${microinfra.scheduler.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>scheduler-core</artifactId>
				<version>${microinfra.scheduler.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>scheduler-client</artifactId>
				<version>${microinfra.scheduler.version}</version>
			</dependency>
			
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>push-commons</artifactId>
				<version>${microinfra.push.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>push-core</artifactId>
				<version>${microinfra.push.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>push-client</artifactId>
				<version>${microinfra.push.version}</version>
			</dependency>
			
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>report-commons</artifactId>
				<version>${microinfra.report.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>report-core</artifactId>
				<version>${microinfra.report.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>report-client</artifactId>
				<version>${microinfra.report.version}</version>
			</dependency>
			
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>rulengine-commons</artifactId>
				<version>${microinfra.rulengine.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>rulengine-core</artifactId>
				<version>${microinfra.rulengine.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>rulengine-client</artifactId>
				<version>${microinfra.rulengine.version}</version>
			</dependency>
			
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>workflow-commons</artifactId>
				<version>${microinfra.workflow.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>workflow-core</artifactId>
				<version>${microinfra.workflow.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>workflow-client</artifactId>
				<version>${microinfra.workflow.version}</version>
			</dependency>
			
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>sysiam-commons</artifactId>
				<version>${microinfra.sysiam.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>sysiam-core</artifactId>
				<version>${microinfra.sysiam.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>sysiam-client</artifactId>
				<version>${microinfra.sysiam.version}</version>
			</dependency>
			
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>order-commons</artifactId>
				<version>${microinfra.order.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>order-core</artifactId>
				<version>${microinfra.order.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>order-client</artifactId>
				<version>${microinfra.order.version}</version>
			</dependency>
			
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>payment-commons</artifactId>
				<version>${microinfra.payment.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>payment-core</artifactId>
				<version>${microinfra.payment.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>payment-client</artifactId>
				<version>${microinfra.payment.version}</version>
			</dependency>
			
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>promotion-commons</artifactId>
				<version>${microinfra.promotion.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>promotion-core</artifactId>
				<version>${microinfra.promotion.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>promotion-client</artifactId>
				<version>${microinfra.promotion.version}</version>
			</dependency>
			
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>parking-commons</artifactId>
				<version>${microinfra.parking.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>parking-core</artifactId>
				<version>${microinfra.parking.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>parking-client</artifactId>
				<version>${microinfra.parking.version}</version>
			</dependency>
			
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>charging-commons</artifactId>
				<version>${microinfra.charging.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>charging-core</artifactId>
				<version>${microinfra.charging.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>charging-client</artifactId>
				<version>${microinfra.charging.version}</version>
			</dependency>
			
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>passport-core</artifactId>
				<version>${microinfra.passport.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>admin-core</artifactId>
				<version>${microinfra.admin.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>operation-core</artifactId>
				<version>${microinfra.operation.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>finance-core</artifactId>
				<version>${microinfra.finance.version}</version>
			</dependency>
			<dependency>
				<groupId>com.microinfra</groupId>
				<artifactId>custservice-core</artifactId>
				<version>${microinfra.custservice.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-toolchains-plugin</artifactId>
					<version>${maven.toolchains.plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-antrun-plugin</artifactId>
					<version>${maven.antrun.plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>${maven.compiler.plugin.version}</version>
					<configuration>
						<source>${java.version}</source>
						<target>${java.version}</target>
					</configuration>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-resources-plugin</artifactId>
					<version>${maven.resources.plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-source-plugin</artifactId>
					<version>${maven.source.plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-jar-plugin</artifactId>
					<version>${maven.jar.plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-assembly-plugin</artifactId>
					<version>${maven.assembly.plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>${maven.surefire.plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>com.google.code.maven-replacer-plugin</groupId>
					<artifactId>replacer</artifactId>
					<version>${maven.replacer.plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-enforcer-plugin</artifactId>
					<version>${maven.enforcer.plugin.version}</version>
					<executions>
						<execution>
							<id>enforce-banned-dependencies</id>
							<goals>
								<goal>enforce</goal>
							</goals>
							<configuration>
								<rules>
									<!-- <requireMavenVersion> <version>3.2.3</version> </requireMavenVersion> -->
									<!-- <requireJavaVersion> <version>1.8</version> </requireJavaVersion> -->
									<bannedDependencies>
										<!-- <searchTransitive>true</searchTransitive> -->
										<!-- <excludes> -->
										<!-- <exclude>commons-logging</exclude> -->
										<!-- <exclude>aspectj:aspectj*</exclude> -->
										<!-- <exclude>org.springframework</exclude> -->
										<!-- </excludes> -->
										<!-- <includes> -->
										<!-- <include>org.springframework:*:4.0.*</include> -->
										<!-- </includes> -->
									</bannedDependencies>
								</rules>
								<fail>true</fail>
							</configuration>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-dependency-plugin</artifactId>
					<version>${maven.dependency.plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>exec-maven-plugin</artifactId>
					<version>${exec.maven.plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-install-plugin</artifactId>
					<version>${maven.install.plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-release-plugin</artifactId>
					<version>${maven.release.plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-maven-plugin</artifactId>
					<version>${maven.springboot.plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.sonarsource.scanner.maven</groupId>
					<artifactId>sonar-maven-plugin</artifactId>
					<version>${maven.sonar.plugin.version}</version>
				</plugin>
			</plugins>
		</pluginManagement>
		
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>flatten-maven-plugin</artifactId>
				<version>1.7.0</version>
				<configuration>
					<updatePomFile>true</updatePomFile>
					<flattenMode>resolveCiFriendliesOnly</flattenMode>
				</configuration>
				<executions>
					<execution>
						<id>flatten</id>
						<phase>process-resources</phase>
						<goals>
							<goal>flatten</goal>
						</goals>
					</execution>
					<execution>
						<id>flatten.clean</id>
						<phase>clean</phase>
						<goals>
							<goal>clean</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
	
	<profiles>
		<profile>
			<id>default</id>
			<activation>
				<activeByDefault>true</activeByDefault>
				<jdk>[17,)</jdk>
			</activation>
			<properties>
				<maven.compiler.source>17</maven.compiler.source>
				<maven.compiler.target>17</maven.compiler.target>
			</properties>
			<dependencies />
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-toolchains-plugin</artifactId>
						<configuration>
							<toolchains>
								<jdk>
									<version>17</version>
									<vendor>oracle</vendor>
								</jdk>
							</toolchains>
						</configuration>
						<executions>
							<execution>
								<goals>
									<goal>toolchain</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-compiler-plugin</artifactId>
						<configuration>
							<source>17</source>
							<target>17</target>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>

</project>